### ISSUE TITLE
Jenkins-Junit not finding tests in test results history

### ISSUE THREAD

**Issue by hiddenshadow21** [gfoidl/trx2junit#102]
# Problem
Jenkins show empty build history list for tests.

Trx2Junit creates tag `<testcase/>` with attributes `name=FullyQualifiedTestName` and `classname=FullyQualifiedClassName`. This leads to double usage of namespace in test result name and somehow breaks Jenkins from finding build with given test in history.

![image](https://user-images.githubusercontent.com/48121604/176171663-4bfe0270-b58e-4485-8cd7-da367085c90c.png)

# Solution I found
Do not use fully qualified name in  `<testcase>` `name` attribute.

# Expected

Trx2Junit creates tag `<testcase/>` with attributes `name=TestName` and `classname=FullyQualifiedClassName`.

**Comment by gfoidl** [comment]
@hiddenshadow21 thanks for the analysis.

Just a question: what test-framework do you use? 
XUnit? In the test-data I see the behavior you described. It's for XUnit, but not for NUnit and MSTest.

Will provide a fix then.

**Comment by gfoidl** [comment]
E.g. it's https://github.com/gfoidl/trx2junit/blob/50432b342c3219948ba49a0d30481c884afce80e/tests/trx2junit.Core.Tests/data/trx/nunit.trx#L21 (NUnit) vs https://github.com/gfoidl/trx2junit/blob/50432b342c3219948ba49a0d30481c884afce80e/tests/trx2junit.Core.Tests/data/trx/xunit.trx#L24 (XUnit). Look at `className` and `name` attributes.

So the test-runners itself write that info, trx2junit just uses these values and emits the jUnit.

Nevertheless this should be fixed up (here).

**Comment by hiddenshadow21** [comment]
Yes, I'm using XUnit.

**Comment by gfoidl** [comment]
@hiddenshadow21 [new release](https://github.com/gfoidl/trx2junit/releases/tag/v2.0.1) with that fix is out.

Thanks for reporting that issue!
