### ISSUE TITLE
Timestamp and error message conversion

### ISSUE THREAD

**Issue by maximusmp** [gfoidl/trx2junit#104]
Hello,

I am currently converting the attached "test.trx" file to the attached "test.xml" file. 
[test.zip](https://github.com/gfoidl/trx2junit/files/9071242/test.zip)

I have two requests:
1. Would it be possible to convert the time zone of the timestamp? In the source file it's, e.g., 2022-07-08T11:59:02.3117362+02:00 but the converted one is 2022-07-08T11:59:03. The expected result could be 2022-07-08T09:59:03;
2. You can see that the error message is repeated in the converted file:

```
<failure message="Assert.AreEqual failed. Expected:&lt;1&gt;. Actual:&lt;2&gt;. " type="not specified"><![CDATA[Assert.AreEqual failed. Expected:<1>. Actual:<2>. 
   at UnitTestProject1.UnitTest1.TestMethod1() in C:\Users\massimiliano.piatto\source\repos\UnitTestProject1\UnitTestProject1\UnitTest1.cs:line 12]]></failure>
```

Would it be possible to indicate only the entire CDATA string in the "message" attribute without providing other strings?

Thank you so much for your work!

### Further technical details
trx2junit-version: v2.0.1
Operating system: Windows 11
Visual Studio version: v17.2.5

**Comment by gfoidl** [comment]
ad point 1: created https://github.com/gfoidl/trx2junit/issues/105 to track this, makes sense 👍🏻 

ad point 2: hm, this got requested in https://github.com/gfoidl/trx2junit/pull/100#issuecomment-1141359849 to work for GitLab. TBH I don't know what's the ideal situation here...

**Comment by maximusmp** [comment]
> ad point 1: created #105 to track this, makes sense 👍🏻

Thanks!

> ad point 2: hm, this got requested in [#100 (comment)](https://github.com/gfoidl/trx2junit/pull/100#issuecomment-1141359849) to work for GitLab. TBH I don't know what's the ideal situation here...

I see, and I have the opposite need because I'm importing the file in Polarion and it appends automatically the "message" attribute and the content of the node:
![immagine](https://user-images.githubusercontent.com/108924385/177978677-ee383daf-e17b-4436-9c31-8ac07a20f9ce.png)

How about an input option to choose from, if repeating the "message" attribute in the content of the "failure" node or not? Or, alternatively, letting the message attribute empty and writing all in the content of the node.

**Comment by gfoidl** [comment]
> How about an input option to choose from, if repeating the "message" attribute in the content of the "failure" node or not?

Sounds good. Will add something like this.
Leaving the message-attribuet may break other use-cases, so I fear that's not a good option.

**Comment by maximusmp** [comment]
Wonderful, thank you!

**Comment by gfoidl** [comment]
PR https://github.com/gfoidl/trx2junit/pull/108 is ready 😄 
Will create a new release once CI is finished (Edit: it's live v2.0.2).

Thanks for reporting these issues!
