### ISSUE TITLE
Incorrect testcase names in xml

### ISSUE THREAD

**Issue by Ray-Barker** [gfoidl/trx2junit#110]
### Summary
When converting trx results to xml testcase name field in xml shows incorrect data

### Steps to reproduce

1. Create trx files with dotnet test --logger "trx;LogFilePrefix=UnitTestResult" -r /reports
2. Run trx2junit /reports/*

### What is the current *bug* behavior?

When there's a dot/dots in a testcase name, only the part after the last dot ends up in xml testcase name field.
For example I get this value:
`testcase name="5 TB&quot;)"`
instead of
`testcase name="SomeText(&quot;1.5 TB&quot;)"`

### What is the expected *correct* behavior?

Unchanged testcase name is in xml

### Further technical details
trx2junit-version: v2.0.3
Operating system: docker

### P.S. 
Tried switching to v1.6.0, this version creates xml files with correct testcase names

**Comment by gfoidl** [comment]
Thanks for the bug-report!

I guess this bug got introduced by https://github.com/gfoidl/trx2junit/pull/103, and I'll provide a fix later today.

**Comment by gfoidl** [comment]
New release [v2.0.4](https://github.com/gfoidl/trx2junit/releases/tag/v2.0.4) with this fix is out.

**Comment by Ray-Barker** [comment]
@gfoidl Big thanks for such a quick response and the fix!
