### ISSUE TITLE
Support for dotnet 6

### ISSUE THREAD

**Issue by bronumski** [gfoidl/trx2junit#112]
Using the mapper for our dot net builds and works great. Only issue is that we need to include .net 5 in our docker images as well as .net 6 which is what our applications require. This results in a bulkier than necessary docker image. Would be nice if the trx2junit had support for the later dotnet 6 SDK.

**Comment by gfoidl** [comment]
I don't follow. What version do you use?

Starting with [version 1.6](https://github.com/gfoidl/trx2junit/releases/tag/v1.6.0) .NET 6 SDK is supported.

Latest version (as of now 2.0.4) supports .NET 6, .NET 5, and .NET Core 3.1 SDKs:
![grafik](https://user-images.githubusercontent.com/5755834/189449031-6ac35148-098a-4cbc-91d5-d7ce3f42cf73.png)
(from [NuGet](https://www.nuget.org/packages/trx2junit/#supportedframeworks-body-tab))

https://github.com/gfoidl/trx2junit/blob/792eebc8dfab5f0e5b72699f7019ea9bf3941ba9/source/trx2junit/trx2junit.csproj#L5

**Comment by bronumski** [comment]
@gfoidl Interesting, we are on 1.5.0 which is what we got when we set the build up a few weeks ago. I will try latest on Monday and we can probably close this out. 

Actually I bet I know what happened. I probably took a direct link to the specific version and we ended up just installing that without realising there were later versions 🤦

**Comment by gfoidl** [comment]
Glad that issue could be solved 👍🏻

**Comment by bronumski** [comment]
@gfoidl - Using latest version (2.0.4), looks to be working fine. Thank you.

P.S: Just checked out your profile 😄 very nice, I used to do a lot of junior ski racing in Alpback back in the 90's but stopped short of FIS. World class effort, I tip my hat to you sir.

**Comment by gfoidl** [comment]
Thanks 😄❤️
