### ISSUE TITLE
"Cannot get required symbol SSL_set_alpn_protos from libssl" when installing trx2junit (.NET 7)

### ISSUE THREAD

**Issue by steingran** [gfoidl/trx2junit#117]
### Summary
We have a build script running on Bitbucket Pipelines that has been running just fine. Today we updated to .NET 7, and we get this message when attempting to run this command: '/usr/share/dotnet/dotnet tool install -g trx2junit': "Cannot get required symbol SSL_set_alpn_protos from libssl"

### Steps to reproduce

    wget https://dot.net/v1/dotnet-install.sh
    chmod a+x dotnet-install.sh
    export PATH="$PATH:/root/.dotnet/tools"
    ./dotnet-install.sh -c 7.0 --install-dir /usr/share/dotnet
    apt-get update && apt-get install -y icu-devtools
    cd test/Project.UnitTests
    # Run tests
    docker-compose up --detach
    /usr/share/dotnet/dotnet tool install -g trx2junit

### What is the current *bug* behavior?

* We get the error message "Cannot get required symbol SSL_set_alpn_protos from libssl" when attempting to install trx2junit with .NET 7 SDK installed

### What is the expected *correct* behavior?

* trx2junit is installed as a global tool

### Relevant logs and/or screenshots
![image](https://user-images.githubusercontent.com/22586339/200870703-c7b46455-f8d3-4419-b0d9-8ae91ad008ff.png)

Tried to update libssl by adding "libssl-dev" to the line starting with apt-get, but this had no effect, the error message stayed the same

### Further technical details
trx2junit-version: v2.0.4
Operating system: Ubuntu 14.04.5 LTS

**Comment by steingran** [comment]
And the problem was solved by using the official .NET 7 image instead of installing .NET 7 SDK ourselves: mcr.microsoft.com/dotnet/sdk:7.0 

Changed the script to this:

    cd test/Project.UnitTests
    docker-compose up --detach
    dotnet tool install -g trx2junit`

What was the underlying problem really is not clear. But this is a workaround at least.

**Comment by gfoidl** [comment]
> What was the underlying problem really is not clear.

I'm not sure either, but guessing that a [Linux package dependencies](https://github.com/dotnet/core/blob/main/release-notes/6.0/linux-packages.md) was missed -- and the official .NET 7 image has these installed.

Anyway: glad that you fond a working solution.

In https://github.com/gfoidl/trx2junit/issues/115 there's the idea to provide a AOT-compiled (self contained) app for _trx2junit_, so no .NET global tool installation is needed. Would something like this help you? Also maybe bundled as deb-package, so the prerequisites could be checked there.
But TBH I have no timeline for this, just as thought so far.
