### ISSUE TITLE
support mstest `Warning` outcomes

### ISSUE THREAD

**Issue by ryepup** [gfoidl/trx2junit#12]
In some circumstances mstest can generate XML like:

```xml
<TestRun ...>
  <ResultSummary outcome="Warning" ...>   <!-- lots of other stuff --> </ResultSummary>
  <!-- lots of other stuff -->
</TestRun>
```

## Expected behavior: 

trx2junit parses the file and writes a junit-formatted xml file

## Actual behavior

trx2junit fails with `Requested value 'Warning' was not found.` when parsing XML

PR coming shortly.

**Comment by gfoidl** [comment]
@ryepup thx for pointing out and submitting the PR 👍

**Comment by gfoidl** [comment]
Closing as #13 got merged.
