### ISSUE TITLE
Officially support .NET 8

### ISSUE THREAD

**Issue by yangchoo** [gfoidl/trx2junit#120]
I noticed https://github.com/gfoidl/trx2junit/pull/118/files but the official documentation does not mention .NET 8 support.

I wanted to double-check if there are any plans for an official .NET 8 release?

**Comment by gfoidl** [comment]
Thanks for the reminder -- I forgot to release it, which got done now: https://github.com/gfoidl/trx2junit/releases/tag/v2.1.0 (just need to wait for NuGet to be ready).
