### ISSUE TITLE
The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')

### ISSUE THREAD

**Issue by HassanJbara** [gfoidl/trx2junit#121]
### Summary

The tools fails on computers with a timezone other than UTC due to the error `The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')`

### Steps to reproduce

* Make trx report
* Set computer timezone to anything other than UTC
* Use the tool to convert the trx report

### What is the current *bug* behavior?

* The trx2junit tool returns `The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')`

### What is the expected *correct* behavior?

* The trx2junit tool returns an xml file

### Relevant logs and/or screenshots

Changing the timezone to UTC fixed the problem. [See this thread](https://stackoverflow.com/questions/13799214/the-utc-time-represented-when-the-offset-is-applied-must-be-between-year-0-and-1).

### Further technical details
trx2junit-version: v2.1.0
Operating system: Windows 11

**Comment by gfoidl** [comment]
I'm not able to reproduce this (and there are lot of other user that use the tool w/o such issues).
Do you have a special trx-file that you can share? Maybe the problem stems from there, and I'd like to investigate this.

**Comment by HassanJbara** [comment]
> I'm not able to reproduce this (and there are lot of other user that use the tool w/o such issues). Do you have a special trx-file that you can share? Maybe the problem stems from there, and I'd like to investigate this.

I'm not sure I can share the trx report with you since it's an internal project, but maybe you can send me a file and I'll try and see if it really has something to do with my file.

**Comment by gfoidl** [comment]
In https://github.com/gfoidl/trx2junit/tree/master/tests/trx2junit.Core.Tests/data/trx you find some trx-files that are used withing this project for testing.

If you find a difference that causes the troubles, it would be nice when you could patch such a file so that file can then be used for validation. Thanks in advance!

**Comment by HassanJbara** [comment]
> In https://github.com/gfoidl/trx2junit/tree/master/tests/trx2junit.Core.Tests/data/trx you find some trx-files that are used withing this project for testing.
> 
> If you find a difference that causes the troubles, it would be nice when you could patch such a file so that file can then be used for validation. Thanks in advance!

I just tried one of the examples and it worked. I also found out that it's the logs of some specific tests that are causing this issue on our end, so I'll investigate this further later and report back to you if needed. Thank you for your time!
