### ISSUE TITLE
Feature request: handle multiple trx files

### ISSUE THREAD

**Issue by ryepup** [gfoidl/trx2junit#14]
Some of our repositories have multiple test projects that create multiple trx files. I'd like to be able to run a command like:

```bash
$ trx2junit projectCore.trx projectClient.trx projectServer.trx
```
and produce one `junit.xml` file that covers all three. I figure set of command-line options leaves `trx2junit` backwards compatible.

Would you be open to this feature? I'd be open to contributing it.

**Comment by ryepup** [comment]
I have this implemented in https://github.com/InfiniteEnergy/trx2junit/tree/multiple-trx-files, on top of the patch from #13.

Will submit a pull request after #13 is merged.

**Comment by ryepup** [comment]
I think I might be able to do something much simpler here, please ignore https://github.com/InfiniteEnergy/trx2junit/tree/multiple-trx-file.

My end goal is [gitlab junit integration](https://docs.gitlab.com/ee/ci/junit_test_reports.html), I think combining to one `junit.xml` might not be needed. I think something like this would work for me:

```shell
$ trx2junit projectCore.trx projectClient.trx projectServer.trx
Wrote projectCore.xml
Wrote projectClient.xml
Wrote projectServer.xml
```

**Comment by ryepup** [comment]
I think https://github.com/InfiniteEnergy/trx2junit/tree/varyargs is the simpler implementation

**Comment by gfoidl** [comment]
> Would you be open to this feature? 

Yes, I'm open to such a feature. This would be an ehancement over writing the command itself multiple times.

https://github.com/gfoidl/trx2junit/issues/14#issuecomment-420267936 (varyargs-branch) looks quite good, and I'm happy if you can submit a PR for this.

**Comment by ryepup** [comment]
will do after #13

**Comment by gfoidl** [comment]
Closing as https://github.com/gfoidl/trx2junit/pull/16 got merged.
