### ISSUE TITLE
Run trx2junit with file parameter returns "Path cannot be empty string or whitespaces"

### ISSUE THREAD

**Issue by subprime** [gfoidl/trx2junit#26]
### Summary

After install the trx2junit as global tool I've try it on the console with an trx report. It fails with the Output 
"Path cannot be the empty string or all whitespace. Parameter name: path"

### Steps to reproduce

* Make trx report

### What is the current *bug* behavior?

* The trx2junit tool returns "Path cannot be the empty string or all whitespace.
Parameter name: path"

### What is the expected *correct* behavior?

* The trx2junit tool returns an xml file

### Relevant logs and/or screenshots

![grafik](https://user-images.githubusercontent.com/17912160/50006224-4a8d4f00-ffad-11e8-8d44-6abecacbffc6.png)

### Further technical details
Operating system: Windows 10
IDE: Visual Studio 2017

**Comment by gfoidl** [comment]
@subprime thanks for reporting this.

With the [latest version](https://www.nuget.org/packages/trx2junit/1.2.1) I'm not able to reproduce this.
Can you please comment what version you use? 
Unfortunately there is not inbuilt way to display the version in use -- I logged https://github.com/gfoidl/trx2junit/issues/27 for this. Right now the version can be seen in the explorere at `C:\Users\%USERNAME%\.dotnet\tools\.store\trx2junit`

**Comment by gfoidl** [comment]
Ahhh, now I have it. Will submit a PR soon.
