### ISSUE TITLE
Test count for separate test suites are being combined

### ISSUE THREAD

**Issue by Itzalive** [gfoidl/trx2junit#32]
### Summary
When a test result file contains multiple test stuites the count of tests in each test suite is not reset each time and is a cumulative total.

### Steps to reproduce

* xUnit project with tests in separate namespaces
* Run dotnet test 
* Make trx report

### What is the current *bug* behavior?

* Each test-suite has a cumulative total of the number of tests.

### What is the expected *correct* behavior?

* Each test-suite has an individual total of the number of tests

### Relevant logs and/or screenshots

[test-results.txt](https://github.com/gfoidl/trx2junit/files/2861948/test-results.txt)

### Further technical details
trx2junit-version: v1.2.2
Operating system: Windows 10

**Comment by gfoidl** [comment]
Thanks for filing this issue -- and for submitting the fix! 👍

**Comment by gfoidl** [comment]
Closing as #34 got merged.
