### ISSUE TITLE
TestDefinitions with multiple UnitTestResults not recognized correclty

### ISSUE THREAD

**Issue by cheng93** [gfoidl/trx2junit#37]
### Summary

When the TRX `TestDefinitions` output does not match the number of `TestEntries` and `Results`.

The JUnit file is a bit dodgy.

Read more here https://github.com/Microsoft/vstest/issues/1989

https://circleci.com/gh/cheng93/TripleTriad/29#tests/containers/0
Is an example 

### Steps to reproduce

* Follow the steps in associated issue
* Create junit file from trx

### What is the current *bug* behavior?

* Counts are wrong in junit

### What is the expected *correct* behavior?

* Counts are correct in junit

### Further technical details
trx2junit-version: v1.2.2
Operating system: linux

----

I will try to get
* Unit test
* trx
* junit xml
when I get home/time

**Comment by cheng93** [comment]
[_c626a975d981_2019-04-16_21_17_01_943.trx.txt](https://github.com/gfoidl/trx2junit/files/3086933/_c626a975d981_2019-04-16_21_17_01_943.trx.txt)

[_c626a975d981_2019-04-16_21_17_01_943.xml.txt](https://github.com/gfoidl/trx2junit/files/3086937/_c626a975d981_2019-04-16_21_17_01_943.xml.txt)

**Comment by gfoidl** [comment]
Please help me understand the problem. The essence is: With data driven tests the meta-data of them is not repeated in `TestDefinition`, hence the wrong numbers are shown. Correct?

**Comment by cheng93** [comment]
Yes.

So a `TestDefinition` can have one or many` UnitTestResults`

Each `UnitTestResult` is identified by a `ExecutionId` with a associated `TestId`
Each `TestDefinition` is identified by a `TestId`

**Comment by gfoidl** [comment]
Thx. Will look at the PR (now I understand the problem).
