### ISSUE TITLE
Cannot process multipul files (Windows CMD)

### ISSUE THREAD

**Issue by JayBird2012** [gfoidl/trx2junit#52]
### Summary
When trying to process multiple files in a Windows CMD (which can handle wild cards) it will not process 

### Steps to reproduce

* Make trx reports
*  Open CMD
* Run Cmd: 

"C:\Users\USER\source\repos\folder\myproject\TestResults\*.trx"

### What is the current *bug* behavior?

* The trx2junit tool returns "The filename, directory name, or volume label syntax is incorrect : trx2junit "C:\Users\USER\source\repos\folder\myproject\TestResults\*.trx"
"

### What is the expected *correct* behavior?

* The trx2junit tool returns an ,many xml file

trx2junit-version: v1.2.2
Operating system: Windows 10

**Comment by gfoidl** [comment]
> Windows CMD (which can handle wild cards)

It can handle the wildcards, but not the expansion of them, as this is a prerequsite.
> `# for shells that handle wildcard expansion:`

When looking at the arguments (`string[] args`) that are given to the process the behavior is different between _bash_ and _cmd_. Demo is executed from the build-output-dir.

**Bash**:
```bash
$ dotnet trx2junit.dll  ../../../../../tests/trx2junit.Tests/data/*.trx
../../../../../tests/trx2junit.Tests/data/mstest.trx
../../../../../tests/trx2junit.Tests/data/mstest-datadriven.trx
../../../../../tests/trx2junit.Tests/data/mstest-datadriven-no-failures.trx
../../../../../tests/trx2junit.Tests/data/mstest-ignore.trx
../../../../../tests/trx2junit.Tests/data/mstest-warning.trx
../../../../../tests/trx2junit.Tests/data/nunit.trx
../../../../../tests/trx2junit.Tests/data/nunit-datadriven.trx
../../../../../tests/trx2junit.Tests/data/nunit-ignore.trx
../../../../../tests/trx2junit.Tests/data/nunit-memberdata.trx
../../../../../tests/trx2junit.Tests/data/nunit-no-tests.trx
../../../../../tests/trx2junit.Tests/data/xunit.trx
../../../../../tests/trx2junit.Tests/data/xunit-datadriven.trx
../../../../../tests/trx2junit.Tests/data/xunit-ignore.trx
../../../../../tests/trx2junit.Tests/data/xunit-memberdata.trx
```

**Cmd**:
```
> dotnet trx2junit.dll ..\..\..\..\..\tests\trx2junit.Tests\data\*.trx
..\..\..\..\..\tests\trx2junit.Tests\data\*.trx
```

So _cmd_ will not expand the wildcard.

But I'll have a look and try to incorporate this. Thx for pointing out.

**Comment by JayBird2012** [comment]
Thanks for the reply here. I am perhaps being a bit thick here. 

Can a method be made inside a .cs file to process them or a batch file. Or is there No way for Windows to process many files? 

The only reason i ask is my xUnit tests are run say 40 times a day. I'm trying to process all 40 in some sort of Job

**Comment by gfoidl** [comment]
I'm going to handle the expansion in the code. If there's an asteriks `*`, so expand it. Shouldn't be that hard to fix.
