### ISSUE TITLE
Can not use this tool after installed by suggestion way

### ISSUE THREAD

**Issue by hamgeorge** [gfoidl/trx2junit#59]
### Summary
Using `dotnet tool install -g trx2junit` in Centos7 by the recommend  way, but it doesn't work.

### Steps to reproduce
1. First, use CLI to install this tool: `dotnet tool install -g trx2junit`
2. Add this tool the Path: `export PATH="$PATH:/root/.dotnet/tools"`
3. Then use this tool to convert my report: `trx2junit _99d190d23823_2019-11-07_07_23_00.trx`
* Make trx report

### What is the current *bug* behavior?
```
A fatal error occurred, the required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/root/.dotnet/tools/.store/trx2junit/1.2.6/trx2junit/1.2.6/tools/netcoreapp2.1/any/].
If this is a framework-dependent application, install the runtime in the default location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.
```

### What is the expected *correct* behavior?
The above command should work. And there should be a file with same name under the TestResults folder.

### Relevant logs and/or screenshots
```
A fatal error occurred, the required library libhostfxr.so could not be found.
If this is a self-contained application, that library should exist in [/root/.dotnet/tools/.store/trx2junit/1.2.6/trx2junit/1.2.6/tools/netcoreapp2.1/any/].
If this is a framework-dependent application, install the runtime in the default location [/usr/share/dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location.
```
### Further technical details
trx2junit-version: v1.2.6
Operating system: docker image Linux-dotnetcore-sdk-2.1

**Comment by gfoidl** [comment]
Falls this under https://github.com/dotnet/cli/issues/9114?

**Comment by hamgeorge** [comment]
I got the solution. Due to my docker image install the dotnet core SDK by manually, so, I need add my sdk path to the PATH, like this: export DOTNET_ROOT="/opt/dotnet-sdk"
