### ISSUE TITLE
JUnit2Trx

### ISSUE THREAD

**Issue by yanlend** [gfoidl/trx2junit#60]
Is there a tool that converts test results in the opposite way? It would be valuable for Azure DevOps, where some functionality only works with **trx** results

Can your tool be extended to do this conversion?

**Comment by gfoidl** [comment]
Yes it can be extended. The models are there, so it's "just" reading, transforming and writing back.

Right now I don't have any clue for the usage therefore. E.g. with `dotnet test` you can get trx-results, so they can be used by Azure DevOps directly.
What scenario do you have in mind?

**Comment by yanlend** [comment]
The scenario is for all languages that are not `dotnet` and thus cannot export a trx file. My use case would be `pytest`, which exports junit files. So I would need to convert exactly in the opposite direction, junit2trx

**Comment by gfoidl** [comment]
Thanks for the motivation. I'll have a look (later today hopefully).

**Comment by gfoidl** [comment]
According to [Publish Test Results task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml) junit is supported.

[Build Python apps](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/python?view=azure-devops) shows an example with _pytest_.

Does this work for you?

**Comment by yanlend** [comment]
Yes, this tool does work with junit, but it uploads the test result not as a test result work item, which is what I would need for my further processing with [Modern Requirements](https://www.modernrequirements.com/).

[Specsync](https://specsolutions.gitbook.io/specsync/important-concepts/synchronizing-automated-test-cases) works with .NET to upload the result as a work item, but not with other [tools](https://specsolutions.gitbook.io/specsync/important-concepts/using-specsync-with-cucumber).

I agree that this might be a somewhat specialized use case...

**Comment by gfoidl** [comment]
Can you please attach some typical junit files?
* one without any errors / failures in tests
* one with errors / failures in tests
* maybe one with skipped tests and passed tests

So I can verify the behavior.
