### ISSUE TITLE
xml file doesn't have all the details which it suppose to be, it looks quite  empty

### ISSUE THREAD

**Issue by jsingh-qualitrol** [gfoidl/trx2junit#74]
@gfoidl 
I too noticed that the converted file is quite empty. 
And my need is to convert the file of trx and import it to QMetry  (addon to Jira). They provided some sample xml which they are supporting. 
Now, I need to make sure the converted file should be quite similar to QMetry file else it would not get imported. So, i shared it with you as the converted xml file was looking empty.

_Originally posted by @jsingh-qualitrol in https://github.com/gfoidl/trx2junit/pull/69#issuecomment-644331653_

**Comment by gfoidl** [comment]
Can you please put every information needed into the description?
I.e. what output do you expect exactely (xml-schema prefered). I don't want to search for this information by myself, at least as this is a use-case which is not relevant to me, and so if I put my effort into enabling this for you, I'd expect that you make this as easy as possible for me to do.

**Comment by jsingh-qualitrol** [comment]
Hello @gfoidl 
Sure i will mention all details related to this. And really appreciate that you would work on it.

Current version of trx2Junit - 1.3.1
I had converter trx file and the xml file which was output is 
[TestResults1.txt](https://github.com/gfoidl/trx2junit/files/4797328/TestResults1.txt)

Now my need is to import this xml to QMetry (add on to Jira ) . Qmetry has some specific xml-schema and they want the input in there format. The sample xml from QMetry is attached for reference:
[JUnitSample.txt](https://github.com/gfoidl/trx2junit/files/4797346/JUnitSample.txt)

Below is the link you may refer if needed :
https://qmetrysupport.atlassian.net/wiki/spaces/QTM4J/pages/1000867047/Test+using+JUnit

Please let me know if you want any other details.
Thanks for your help.

**Comment by gfoidl** [comment]
> Qmetry has some specific xml-schema

The only difference I can see is that the sample given includes the namespace, whilst plain JUnit doesn't need / has this.
Are there any other differences? (Maybe I'm overseeing something).

If so, then this could be solved with an additional cli-flag to include the namespaces in the output.
(I thinks this valuable --> https://github.com/gfoidl/trx2junit/issues/75)

**Comment by gfoidl** [comment]
> includes the namespace

I'm even not sure if this is true. In the linked confluence page it isn't shown, in the file download there it is.

Honestly, I have no idea what should be changed and what is expected.
The tool outputs JUnit-xml which validates -- and that's my (initial) intention to write this tool.
If this is a QMetry thing, than they should adopt to read standard JUnit as "everything" else does.

When I don't have clear information what to do, then this issue isn't actionable.

**Comment by jsingh-qualitrol** [comment]
Hello @gfoidl 

I am not sure if all the content of trx is getting converted in xml. The xml after conversion is showing only 30 test cases all as pass. However, in trx we have different number. In jenkins we have same as trx .
![image](https://user-images.githubusercontent.com/33225387/85885490-09146b80-b802-11ea-9c0c-b0ee610d9160.png)





[TestResults_xml.txt](https://github.com/gfoidl/trx2junit/files/4838418/TestResults_xml.txt)
[TestResults_trx.txt](https://github.com/gfoidl/trx2junit/files/4838422/TestResults_trx.txt)
Please let me know why we don't see same number in both the doc.

**Comment by gfoidl** [comment]
The tool reads the trx-file contents https://github.com/gfoidl/trx2junit/blob/3fc197e083da95bd0e407e6d0f32bb147339b5a1/source/trx2junit/Internal/trx2junit/TrxTestResultXmlParser.cs#L44-L52

With your file the content is
```xml
<ResultSummary outcome="Failed">
    <Counters total="102" executed="96" passed="37" error="0" failed="20" ...
```
If I open this trx in Visual Studio I see the same numbers.

Then it reads the `UnitTestResult`s https://github.com/gfoidl/trx2junit/blob/3fc197e083da95bd0e407e6d0f32bb147339b5a1/source/trx2junit/Internal/trx2junit/TrxTestResultXmlParser.cs#L84-L88

Instead of the element `<UnitTestResult>` your file has `<TestResultAggregation>` elements (which has the same content on a first look).
That's why no actual results are read.

The schema https://github.com/gfoidl/trx2junit/blob/3fc197e083da95bd0e407e6d0f32bb147339b5a1/schemas/vstst.xsd#L433 shows this type, so this one should be supported definitely.

Out of interest: how did you generate this trx-file?

**Comment by jsingh-qualitrol** [comment]
Thanks for response. 
This trx file is generated from Jenkins by MSTest plugin.

**Comment by gfoidl** [comment]
To make development easier for me, can you provide a stripped down trx-file please?
E.g. the output from simple tests like https://github.com/gfoidl/trx2junit/blob/3fc197e083da95bd0e407e6d0f32bb147339b5a1/samples/XUnitSample/SimpleTests.cs#L6

I'd like to add this to the unit-tests and with just a few tests in trx-file it's easier to develop and debug than with 100 tests :wink:
Thanks in advance.

I'll hope to provide a fix in the next days (hopefully tomorrow).

**Comment by gfoidl** [comment]
A quick fix produces for the above trx-file 
[TestResults.xml.txt](https://github.com/gfoidl/trx2junit/files/4842529/TestResults.xml.txt)

Please verfiy if this matches your needs.
In the meantime I'll try to match the trx-scheme more closely.

**Comment by jsingh-qualitrol** [comment]
Hello,
With first glance i think it has appended some more details. By when i could get another version of trx2xml?

**Comment by gfoidl** [comment]
> when i could get another version of trx2xml?

1. accepts QMetry the transformed file from https://github.com/gfoidl/trx2junit/issues/74#issuecomment-650782735?
1. I'll create a PR
1. if needed a preview-version to test more thoroughly will be created (this one you can use)
1. a new release is done

**Comment by gfoidl** [comment]
Also please

> can you provide a stripped down trx-file please?

otherwise it's quite hard for me to have the correct inputs. 
Generating some from the schema may or may not match real-world trx-files :wink:

**Comment by jsingh-qualitrol** [comment]
Hello,
Please find the stripped trx file:
[TestResults.txt](https://github.com/gfoidl/trx2junit/files/4842612/TestResults.txt)
1)accepts QMetry the transformed file from #74 (comment)?
Ans) Today, i am facing parse exception with QMetry so unable to check it. However, i had raised a ticket to QMetry team.

I had to demo it  on Tuesday, so i need the updated release, if possible.

Thanks for prompt response!

**Comment by gfoidl** [comment]
Thanks. PR will come soon, then you have a workable version of the tool. Instruction will follow in the PR.

**Comment by jsingh-qualitrol** [comment]
Just for your reference : QMetry has following Schema which is acceptable:
<?xml version="1.0" encoding="UTF-8"?>

-<testsuite failures="1" skipped="0" errors="0" tests="5" time="0.036" name="com.CalculatorTest" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">


-<properties>

<property name="sun.desktop" value="windows"/>

<property name="file.encoding.pkg" value="sun.io"/>

<property name="java.specification.version" value="1.8"/>

<property name="java.vm.vendor" value="Oracle Corporation"/>

</properties>


-<testcase time="0.007" name="testEqual" classname="com.CalculatorTest">

<failure type="java.lang.AssertionError">java.lang.AssertionErrorat com.javacodegeeks.examples.junitmavenexample.CalculatorTest.testEqual11(CalculatorTest.java:59) </failure>


-<system-out>

-<![CDATA[This is executed before each Test
This is exceuted after each Test
]]>
</system-out>

</testcase>

<testcase time="0" name="testSum" classname="com.CalculatorTest"/>

<testcase time="0.001" name="testSubstraction" classname="com.CalculatorTest"/>

<testcase time="0" name="testDivisionException" classname="com.CalculatorTest"/>

<testcase time="0" name="testDivison" classname="com.CalculatorTest"/>

</testsuite>

**Comment by gfoidl** [comment]
I don't see any scheme here... just an error? notice.

**Comment by jsingh-qualitrol** [comment]
[JUnit (2).txt](https://github.com/gfoidl/trx2junit/files/4842663/JUnit.2.txt)
Reference for supported xml schema of QMetry
