### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by AlexGagne** [gfoidl/trx2junit#81]
I have a test file generated by this command:
`dotnet test --logger trx`

However, when I try to convert the file on jrx2unit version 1.4.0 using this command:
`trx2junit .\failing.trx`

I get this error:
`Object reference not set to an instance of an object.`

And the conversion fails. I've attached an anonymized file that reproduces the issue (note: file was renamed from trx to txt so that I could attach it to the issue).
[failing.txt](https://github.com/gfoidl/trx2junit/files/5906584/failing.txt)

If it changes anything, the tests were done in F# originally, although other trx files from F# tests that I have convert successfully.

Edit: The original file had 12 tests, I've edited them out for a smaller file.
Edit2: Please ignore the reference to the PR. I didn't expect this to show up as "mentioned" here and now I can't remove it. Error on my part.

**Comment by gfoidl** [comment]
Thanks for the report, I'll have a look on whats going on.

**Comment by gfoidl** [comment]
OK, problem located.

Current implementation of trx2junit conforms the trx-xml-schema, which requires the `name`-attribute on `TestMethod` --> https://github.com/gfoidl/trx2junit/blob/55b6028f3d5174874eab4982fa239e0a678e96b3/schemas/vstst.xsd#L1574

The trx given above looks like
```xml
<TestMethod codeBase="xxx" adapterTypeName="xxx" className="xxx" />
```
so it's missing the `name`-attribute. Either the tool that generated the trx doesn't conform the trx-schema or the schema evolved and allows this.

Anyway I'll relax trx2junit here, as the resulting junit file validates.

**Comment by gfoidl** [comment]
@AlexGagne I created a [new release](https://github.com/gfoidl/trx2junit/releases/tag/v1.4.1), just need to wait a bit until CI is done and NuGet has indexed it.

Please give it a try...in a couple of minutes.

**Comment by AlexGagne** [comment]
Wow, your response was much faster than I expected! It's working now. I really appreciate it!
