### ISSUE TITLE
Jenkins-JUnit: set status attribute on testcase

### ISSUE THREAD

**Issue by PavanMudigonda** [gfoidl/trx2junit#83]
Could you please include additional junit parameters corresponding to each test case like ‘failure=“false” error=“false” success=“true”. I need these values in my junit XML so I can upload results to Microfocus ALM through Jenkins plugin. Awesome job by the way.

Or if you can include status attribut alone that will also solve my problems. Below screen shot from Jenkins-junit.SDF which has status attribute corresponding to test case![image](https://user-images.githubusercontent.com/29324338/109071236-72b28580-76c1-11eb-8b18-22b945d341b0.jpeg)

**Comment by gfoidl** [comment]
> additional junit parameters corresponding to each test case like ‘failure=“false” error=“false” success=“true”. 

No, as they're not declared in https://github.com/gfoidl/trx2junit/blob/a10c553c9e94195146c048b906a8253da1da360f/schemas/jenkins-junit.xsd#L64-L79

> include status attribut alone

That's possible, as it's declared https://github.com/gfoidl/trx2junit/blob/a10c553c9e94195146c048b906a8253da1da360f/schemas/jenkins-junit.xsd#L77

It's of type `xs:string` so any string-values are allowed. What values should be set for status depending on the result of the testcase? Can you point me to some documentation or ideally provide the values?

**Comment by PavanMudigonda** [comment]
Hi Gunther, thanks for getting back to me quickly. I really appreciate your help. So I checked Jenkins ALM plug-in. The 'status'needs to be set to 1 which indicated test case is passed and set to 0 which indicates the test case is failed. So valid values for status are 1,0. Thanks a lot in advance.

**Comment by gfoidl** [comment]
@mnpawan please give the pre-release a try:

```bash
# deinstall current version
dotnet tool uninstall -g trx2junit

# install preview
dotnet tool install -g trx2junit --version 1.4.2-preview-1 --add-source https://pkgs.dev.azure.com/gh-gfoidl/github-Projects/_packaging/gfoidl-public/nuget/v3/index.json
```

If this is OK, I'll productize the change in a proper version -- now it's just a quick hack.

**Comment by PavanMudigonda** [comment]
@gfoidl Thanks a lot for quick turn around. I have verified the preview and it's working properly and I am see my test case results going to Micro Focus ALM through Jenkins. You can publish fix properly. Have a good day.

**Comment by gfoidl** [comment]
Thanks for confirmation! I'll release the proper version -- will take a couple of minutes until CI is finished.

Have a good day, too 😃
