### ISSUE TITLE
Change Status Atribute values to True/False instead of 1/0

### ISSUE THREAD

**Issue by PavanMudigonda** [gfoidl/trx2junit#85]
Hi Gunther,

I made mistake while testing. Could you change Status Atribute values to True/False instead of 1/0. Sorry for causing you rework. Appreciate if you can fix it. Thanks in advance. 

True: if test case is passed
False: if test case is failed

**Comment by gfoidl** [comment]
I'll update this when some other things need to be done here -- this is a litte change and I don't think it's worth a new version and the current behavior is already documented. But this is also on the good side 😄 as there are environment-variables that allows you to configure what values should be used. See https://github.com/gfoidl/trx2junit/releases/tag/v1.5.0 for further info.

E.g.
```bash
export TRX2JUNIT_JENKINS_TESTCASE_STATUS_SUCCESS=true
export TRX2JUNIT_JENKINS_TESTCASE_STATUS_FAILURE=false

trx2junit ...
```
(or define them in your CI-system globally).

Does this help you?

**Comment by PavanMudigonda** [comment]
Thank you for proving work around with variables. It's working with this way. For now I will use this work around. Thanks a lot.

**Comment by gfoidl** [comment]
Closing as no further action needs to be done.

**Comment by PavanMudigondaTR** [comment]
Thanks Gunther
