### ISSUE TITLE
.NET 6 compatibility

### ISSUE THREAD

**Issue by felschr** [gfoidl/trx2junit#88]
### Summary

`trx2junit` doesn't work with .NET 6.0 SDK.

### Steps to reproduce

Install .NET SDK 6.0 (no other versions), install `trx2junit` and run it.

### What is the current *bug* behavior?

`trx2junit` returns:
```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0 at [/nix/store/ik02f65i5nkiy0qfpn0wz6dskgdqc16j-dotnet-core-combined/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64
```

### What is the expected *correct* behavior?

`trx2junit` should work normally.

### Further technical details
trx2junit-version: v1.5.0
Operating system: NixOS 21.11 (unstable)

**Comment by gfoidl** [comment]
There's https://github.com/gfoidl/trx2junit/pull/86 to tackle this.

Thanks!

**Comment by gfoidl** [comment]
[v1.6.0](https://github.com/gfoidl/trx2junit/releases/tag/v1.6.0) with support for .NET 6.0 is released -- just need to wait for NuGet Gallery to finish validation.

**Comment by felschr** [comment]
Thank you 🥳!
