### ISSUE TITLE
Unhandled Exception with MsTest

### ISSUE THREAD

**Issue by gfoidl** [gfoidl/trx2junit#9]
I got a message via NuGet (that's the reason for https://github.com/gfoidl/trx2junit/issues/7):

```
trx2junit : At line:1 char:1 + trx2junit "C:\files\result.trx" + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:String) [], RemoteException + FullyQualifiedErrorId : NativeCommandError

Unhandled Exception:

System.NullReferenceException: Object reference not set to an instance of an object. at trx2junit.Program.ReadResults(XElement trx) in /root/repo/source/trx2junit/Program.cs:line 73 at trx2junit.Program.ReadTrx(String trxFileName) in /root/repo/source/trx2junit/Program.cs:line 50 at trx2junit.Program.Main(String[] args) in /root/repo/source/trx2junit/Program.cs:line 36
```

It can be confirmed that this is a bug -- cf. https://circleci.com/gh/gfoidl/trx2junit/49

**Comment by jsingh-qualitrol** [comment]
Hello 
Please help me with this error
I am getting exception "Object reference not set to an instance", when i attempt to convert from .trx to xml file 
![image](https://user-images.githubusercontent.com/33225387/83872331-64959100-a74f-11ea-952c-3c22a87c73ca.png)

**Comment by gfoidl** [comment]
@jsingh-qualitrol can you please attach a sample trx-file, so debugging this issue becomes possible?

**Comment by jsingh-qualitrol** [comment]
@gfoidl [

](url)
[New Text Document.txt](https://github.com/gfoidl/trx2junit/files/4745584/New.Text.Document.txt)
Please let me know your findings as i need it badly for my project.

**Comment by gfoidl** [comment]
@jsingh-qualitrol is this the same trx-file than the one which gives the failure from the screenshot?
With this file I get
```
Invalid character in the given encoding. Line 823, position 10.
```
(will have to look into this failure too).

**Comment by jsingh-qualitrol** [comment]
Now, i downgrade the version and i am getting following error with same trx file which i shared with you. 
![image](https://user-images.githubusercontent.com/33225387/84109251-dca9d280-aa3f-11ea-9c3c-2386d78408e2.png)

**Comment by gfoidl** [comment]
Well the problem seems to be that the provided trx-file isn't valid against the [schema](https://github.com/gfoidl/trx2junit/blob/master/schemas/vstst.xsd). There are several validation errors, which are unrelated to this tool and I'm hesistant to alter the implemation to match something that doesn't confirm the standard (because that would open a can of worms).
If I'm wrong please let me know.

How did you create the trx-file? If it's a third-party tool maybe it's best to make this conforming the official MS-schema for trx-files.

**Comment by jsingh-qualitrol** [comment]
This trx file is generated from Jenkins tool, after i run all the test through it.

**Comment by gfoidl** [comment]
Out of interest: why don't you use something like https://plugins.jenkins.io/mstest/ for Jenkins which should work out of the box?

I'll see what is possible here...

**Comment by gfoidl** [comment]
--> https://github.com/gfoidl/trx2junit/issues/68
