### ISSUE TITLE
Release main library separately?

### ISSUE THREAD

**Issue by dstahl-axion** [gfoidl/trx2junit#92]
Hello and thank you so much for this project!

I was wondering if you had any interest in releasing the main code as a separate nuget package / library that could be integrated into other tools such as Nuke.Build? The separate tool requires one extra step to set up / maintain a build server. However, it works so well I don't mind doing it :)

My use case was that I wanted to simplify my unit test running so I have dotnet-vstest output a TRX file (so I don't need a custom logger). But Jenkins was taking 10+ minutes to ingest the TRX file. Converting it to Junit reduced the file size and the import time to a few seconds. Thanks again.

**Comment by gfoidl** [comment]
Just a question if I understood your request correct:
Split the code in a "core" and "tool" part, producing two packages
* trx2junit -- the tool as is produced now
* trx2junit.Core -- the new package that contains the core logic

Is that correct?

If so, yes this can be done. Actually I had this already in mind, but because of YAGNI didn't do so far 😉 
When done, the tool would be a consumer of the core-package too. So we may need to shape the public API of the core library to fit your needs.

**Comment by dstahl-axion** [comment]
That's absolutely correct and exactly what I was suggesting. And I'm not sure if my single request changes the YAGNI status or not 😃 My current build system only needs this tool on a single server so the impact to me is really minimal at this point. However, upgrading a Nuget package in my build project _is_ simpler than upgrading a tool on a build server.

**Comment by gfoidl** [comment]
I'll have a look into it 😃 
This is the trigger for me to do it finally (should have been done from ground off, as having an app / tool as wrapper around a "core" part is almost always a better choice).

**Comment by gfoidl** [comment]
@dstahl-axion in the [new release](https://github.com/gfoidl/trx2junit/releases/tag/v2.0.1) there's a change for https://github.com/gfoidl/trx2junit/issues/95 which may affect you -- assuming you still use the core-part of _trx2junit_.

Console-output isn't written by Core-lib anymore. You can see in the tool-host how to enable it again:
https://github.com/gfoidl/trx2junit/blob/1aaef7bd396a6217ed46f1a98b500e84e94e9cda/source/trx2junit/Program.cs#L19-L20 and https://github.com/gfoidl/trx2junit/blob/1aaef7bd396a6217ed46f1a98b500e84e94e9cda/source/trx2junit/Program.cs#L42-L62
